version: '3'
services:
  gtg-flask-app:
    container_name: gtg-flask-app
    build: ./app
    restart: always
    links:
      - mysql-db
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db


  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql        
